### PR TITLE
Moving from swig to ejs

### PR DESCRIPTION
**Pull request by nanspro**
Converting remaining .swig files to .ejs
PR is part of https://github.com/status-im/status.im/issues/156

### CODE REVIEW

**Comment by nanspro** [comment]
@richard-ramos  could you review this one also?

**Comment by richard-ramos** [comment]
Looks good to me, however I do not have write access to this repository to be able to merge this PR.
@pablanopete, help me with this, please :)

**Review by richard-ramos — APPROVED** [review]

**Comment by samthomson** [comment]
The nimbus site uses swig still, and includes this repo as a submodule. That site will break a little  the next time it is built, unless it is also ported from swig to ejs. Is that on the cards or? @richard-ramos @nanspro @andytudhope 

It seems during the resolution of this issue https://github.com/status-im/status.im/issues/156 that only the status.im site was considered.
I'd be happy to look into porting the Nimbus site to EJS too (consistency++ :upside_down_face: ) Let me know what you guys think.

This is how Nimbus looks otherwise:
Header:
image
Footer:
image

**Comment by andytudhope** [comment]
Yeah, that's not good, and I'm with you on consistency. If you'd like to look into porting the Nimbus site across to ejs, that'd be great @samthomson ❤️

**Comment by samthomson** [comment]
Cool, will start a PR tomorrow while looking at the other JS work (after desktop release).

**Pull request merged**
