### PR TITLE
rough instructioons in the readme on how to work with this workflow

### PR DESCRIPTION
**Pull request by samthomson**
WIP

### CODE REVIEW

**Comment by andytudhope** [comment]
OK cool, let me know when this is ready? What you showed me in that call also had the header, so let me know when you're ready with that, it seemed mostly good to me 👍

**Comment by samthomson** [comment]
Headers in, let me know how you get on :)

**Comment by andytudhope** [comment]
@samthomson it works really nicely, thank you! I added more shared things - let's see what else we can pull out into the common folder: https://github.com/andytudhope/merrymerkle.africa/commit/c6c391b966e94d221e0d8e7eaee1d7e4efd1f4fe

Maybe even some of the styles and JS are candidates? There's definitely more of the header we can pull in... Either way, this is great, thanks. Am going to implement on status.im now as well. Please make sure to hit submit on the Gitcoin bounty so I can pay it out 👍 

It'w worth noting I had an issue pushing back up to this git submodule after adding it with `https` rather than `ssh` as my git is config'd to use that (as are most people at Status'). Maybe we should change that line (though I think https might still be better for CI - let me check).

**Comment by samthomson** [comment]
No worries, happy to help.
ssh +1, go for it. Could always have a separate scripts command just for the CI (if it having an ssh key isn't an option).

Sharing the partial that imports all the common JS files could be in here for sure. Although what about the actual JS files? Since this repo will be added/cloned into the other sites partials folder, maybe we shouldn't add raw JS files here or they'd be in an unexpected (and likely publicly unreachable) location. Maybe a different repo for shared JS files, or does that become too messy? Or just further down the line...

Happy to wrap up on gitcoin if you are, sure you don't want us to wait and do the final implementation on the main sites after the other related tasks are wrapped up?

**Comment by andytudhope** [comment]
OK, will do on the ssh. 

Have already done that in after_footer, but yeah, I agree with you otherwise - likely to become too messy no matter which way we go. The biggest issue I am having now is that the SM is added at a specific commit, so it is not being found by the CI when building directly from the the repo: https://github.com/status-im/status.im/tree/develop/themes/navy/layout/partial

Any ideas how to fix that one? 😅

**Comment by samthomson** [comment]
Ah yes, I think I forgot to write in the readme that repos with submodules should be cloned with `git clone --recursive`.
That is one of the *disadvantages* of using submodules. 
For each static site we should update its readme to have the appropriate clone command (recursive flag).
Let me know how you get on and I'll update the readme accordingly, or we can keep troubleshooting :upside_down_face:

**Comment by andytudhope** [comment]
Do you mean when adding? i.e.

`git submodule add git@github.com:status-im/status.im-partials.git shared-partials --recursive`

**Comment by samthomson** [comment]
No, I mean when first pulling down the project. Presuming the build process/CI runs in a disposable instance, where it clones the repo? Does that makes sense or were you describing a different issue I misunderstood?

**Comment by jakubgs** [comment]
Yup, you either need to do:
```
git clone --recurse-submodules ${REPO}
```
Or after clone run:
```
git submodule update --init --recursive
```

**Comment by samthomson** [comment]
SO answer covering the history of `git clone --recursive` and `git clone --recurse-submodules`

https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

Seems there's a performance option that allows pulling 8 submodules in parallel :smile: not sure we're at that stage yet but good to know :rocket: 

A nice explainer on both submodules and subtrees: https://andrey.nering.com.br/2016/git-submodules-vs-subtrees/

**Pull request merged**
